"use client"
import React, { Suspense, useState } from 'react'
import Head from 'next/head'
import {FaAngleDown, FaBars, FaBell, FaDashcube} from "react-icons/fa"
import { Avatar } from '@mui/material'
import Loading from '../loading'
import Sidebar from '../components/Sidebar'

export const metadata = {
  title: 'Landing page',
  description: 'Generated by create next app',
}

export default function Layout({children, title = "Landing page", keywords="", description=""}) {
     {/* head */}
    <Head>
        <title>{title}</title>
        <meta name='keywords' content={keywords}/>
        <meta name="description" content={description}/>
    </Head>

    // states
    const [showSidebar, setShowSidebar] = useState(true);

  return (
    <div>
      <nav className='bg-white p-2 shadow-md sticky top-0 z-10 flex items-center justify-between container mx-auto'>
          <div className='flex items-center gap-4'>
            <FaBars className='text-black'onClick={() => setShowSidebar(!showSidebar)}/>
            <h1 className='text-black'>E-Recruitment Portal</h1>
          </div>

          <div className='flex items-center gap-4'>
            <div><FaBell className='text-black' /></div>
            <Avatar sx={{width:"30px", height: "30px"}}>P</Avatar>
          </div>
      </nav>


      <Suspense fallback={<Loading/>}>
        <main className='min-h-screen flex gap-2'>
            {showSidebar && 
            <aside className="w-64 shadow-lg h-screen bg-blue-950 p-2 sticky top-0">
                <Sidebar/> 
            </aside>
            }

            <section className='p-2 bg-inherit w-full'>
                {children}
            </section>
        </main>
       </Suspense>
    </div>
  )
}
