import Link from 'next/link'
import './globals.css'
// import Router from "next/router"
import NProgress from 'nprogress'
import "nprogress/nprogress.css"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// NProgress.configure({showSpinner: false})

// Router.events.on('routeChangeStart', () => NProgress.start());
// Router.events.on('routeChangeComplete', () => NProgress.done());
// Router.events.on('routeChangeError', () => NProgress.done());

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
          <title>Landing page</title>
          <meta name="description" content='Generated by create next app' />
      </head>
      <body>
            {children}
      </body>
    </html>
  )
}
